version: '3'
services:
  # GRAPH QL DEVELOPMENT SERVER
  graph-ql-api-development:
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      # API Configurations
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      # OAuth Required Configurations
      - OAUTH_URL
    ports:
      - '80:80'
    volumes:
      - /app/node_modules
      - .:/app
    depends_on:
      - flyway
      - sql-server
      - redis-server
  # MIGRATION CONTAINER (EXECUTES MIGRATION TO SQL SERVER)
  flyway:
    image: boxfuse/flyway
    command: -url=jdbc:sqlserver://sql-server:1433; -user='sa' -password=D3v3lopm3ntGx -connectRetries=60 migrate
    volumes:
      - ./db/migrations:/flyway/sql
    depends_on:
      - sql-server
  # SQL SERVER
  # !!!!!!! please check that your VM have at least 2024 mb RAM memory !!!!!!!
  sql-server:
    image: mcr.microsoft.com/mssql/server
    environment:
      - SA_PASSWORD=D3v3lopm3ntGx
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
  # REDIS SERVER
  redis-server:
    image: redis
    command: redis-server --port 6380 --requirepass D3v3lopm3ntGx
    ports:
      - "6380:6380"
